


      # services:
#   webapplication1:
#     image: ${DOCKER_REGISTRY-}webapplication1
#     build:
#       context: .
#       dockerfile: WebApplication1/Dockerfile
version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: kartverketdb
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345678
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - backend

  kartverketgroup20:
    image: ${DOCKER_REGISTRY-}kartverketgroup20
    build:
      context: .
      dockerfile: KartverketGroup20/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - mariadb
    environment:
      ConnectionStrings__DefaultConnection: "Server=mariadb;Database=kartverketdb;User=root;Password=12345678;"
    networks:
      - backend
    command: bash -c "for i in \$(seq 1 30); do dotnet ef database update && break || (echo 'Waiting for DB...'; sleep 5); done; dotnet KartverketGroup20.dll"

volumes:
  mariadb_data:

networks:
  backend:
